version: "3.9"

services:
  # app コンテナの記述...

  web:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./frontend/:/home/node/app
    tty: true
    ports:
      - 5173:5173